version: '1.0'
name: pipeline-20220219
displayName: pipeline-20220219
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-ce32e9c2
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - npm install && rm -rf ./blog && npm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./blog
  - name: stage-86b9d928
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: shell@agent
        name: execute_shell
        displayName: Shell 脚本执行
        hostGroupID: gitee-go
        script: |-
          # 请在此输入您想执行的脚本
          cp robots.txt docs/.vuepress/blog/robots.txt; cd docs/.vuepress;scp -r blog root@www.apidocs.cn:/usr/local/nginx/html
permissions:
  - role: admin
    members: []
